### ISSUE TITLE
SurveyManager is not getting the right Activity

### ISSUE THREAD

**Issue by HPH92** [Wootric/segment-android-integration-wootric#4]
We are trying to use Wootric through Segment with provided integration (`WootricIntegration`), instead of (`WootricSDK-Android.`) The clean Wootric implementation is working, but we are running into trouble with this.

analytics-integration-wootric:0.1.6
Error in the logcat: `showSurvey: Can not perform this action after onSaveInstanceState`

Our Analytics instance is initialized in "application controller".

What I may see as the problem is the following: 
```
    @Override
    public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
        super.onActivityCreated(activity, `savedInstanceState);`
        wootric = Wootric.init((FragmentActivity) activity, clientId, accountToken);
        updateEndUserAttributes();
    }
```

Is called every time the activity is changed (In our case we are starting with SplashActivity, and then we are going to mainActivity), 
but then in `SurveyManager` line 178

`final FragmentManager fragmentManager = activity.getSupportFragmentManager();`

It still holds the first activitiy (in our case the SplashActivity) instead of changing the reference to mainActivity (currently 'in focus'). For that reason, since FragmentManager is referencing the activity in order to get the support fragment manager, it stumbles on a null reference, which results in the survey not showing up.

What should we do to get the right activity in SurveyManager?

**Comment by ambarwootric** [comment]
Hi @HPH92! Thanks for letting us know about this and we have to look more into it. We will prioritize this issue in the coming sprint and will come up with some solution for you.

**Comment by guthrie-over** [comment]
Hi @ambarwootric have you perhaps got an update for us?

**Comment by guthrie-over** [comment]
Hi @ambarwootric could have an update on these please?
Thank you

**Comment by diegoserranoa** [comment]
Hi @guthrie-over,

Sorry for the long delay in our response. It's been crazy over here.

Just wanted to update you that I was able to replicate the issue and I'm working on a solution. I'll keep posting once I find a solution to this. Maybe you can help us testing the correct solution.

Thank you very much for your patience 🙏

**Comment by diegoserranoa** [comment]
Hello @guthrie-over!

I have a PR out to update our SDK with a fix for this issue. Could you help us test to see if this fixes your issue?

**Comment by HPH92** [comment]
I'm sorry but I don't work on that project anymore. 
But good that a fix was made!

**Comment by diegoserranoa** [comment]
Thanks for replying @HPH92 ! I already got in touch with a dev to test this out.

**Comment by diegoserranoa** [comment]
Issue addressed in https://github.com/Wootric/segment-android-integration-wootric/commit/5965885f90c27a5bc332c84ad06e3315544223cc

Thanks for all the patience 🙏
