### ISSUE TITLE
Crashing when using an Activity that is not extending a FragmentActivity

### ISSUE THREAD

**Issue by riggaroo** [Wootric/segment-android-integration-wootric#5]
Hi there,
We are using this integration in our app and I'm noticing there is a crash when trying to display an Activity that doesn't extend `FragmentActivity`. In this case, I'm referring to using the Play Billing Library (which we cannot modify). 

We are receiving the following crash:
```
 java.lang.ClassCastException: com.android.billingclient.api.ProxyBillingActivity cannot be cast to android.support.v4.app.FragmentActivity
        at com.wootric.analytics.android.integrations.wootric.WootricIntegration.onActivityCreated(WootricIntegration.java:59)
        at com.segment.analytics.IntegrationOperation$1.run(IntegrationOperation.java:39)
        at com.segment.analytics.Analytics.performRun(Analytics.java:1464)
        at com.segment.analytics.Analytics$4$1.run(Analytics.java:455)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I believe this is due to line 59 where a FragmentActivity is expected.
` wootric = Wootric.init((FragmentActivity) activity, clientId, accountToken);`

How would you recommend using this library when an activity doesn't extend `FragmentActivity`?

**Comment by ambarwootric** [comment]
Hi @riggaroo! Thanks for letting us know about this and it's the good point. We will prioritize this issue in the coming sprint and will come up with some solution for you.

**Comment by guthrie-over** [comment]
Hi @ambarwootric have you perhaps got an update for us?

**Comment by guthrie-over** [comment]
Hi @ambarwootric could have an update on these please?
Thank you

**Comment by prabhatjha** [comment]
Hi @guthrie-over and @riggaroo We have not forgotten about it although it seems like that. Ambar has a fix for this issue and currently working on #4.  Some of our engineers have taken time off so it has caused delay on our side. We are hoping that we would release it next week with fix for both this issue and #4 . 

Thanks for your patience. Please feel free to reach out again.

**Comment by diegoserranoa** [comment]
Hi @guthrie-over and @riggaroo I really apologize for the delay on this. I'm currently updating the SDK to bring back support for `Activity`. Code is almost done and I should have the SDK updated between today and tomorrow.

Once again, apologies for the delay and first item on my list is to get you guys going with this! 🙏 

I'll keep you updated with the progress.

**Comment by diegoserranoa** [comment]
hi @guthrie-over and @riggaroo ! I've just released a new version of the integration which solves this issue. Please let us know that everything is working as you expect!

Thanks for all the patience 🙏 sorry this took so long to address.

I'm leaving this issue opened until you can confirm that everything is working.

**Comment by riggaroo** [comment]
@diegoserranoa Thanks so much for fixing this issue. I can confirm that this issue is now fixed 👍 
However, we are still blocked by issue #4, we would really appreciate a fix on that one too, since we would love to get this integration deployed on our app 🙏
